// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaomNQpybR-GVvCfitKTgwMkp1I1R54yU',
    appId: '1:568507595325:web:25d5dbc094d1d528850854',
    messagingSenderId: '568507595325',
    projectId: 'starthack-delta',
    authDomain: 'starthack-delta.firebaseapp.com',
    storageBucket: 'starthack-delta.appspot.com',
    measurementId: 'G-VN09HHTFQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_YYu26K6IivurXEhkElVEWx4BJVPzy8c',
    appId: '1:568507595325:android:8c61180863d1daa2850854',
    messagingSenderId: '568507595325',
    projectId: 'starthack-delta',
    storageBucket: 'starthack-delta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARiBBQZ8m4VXLrTegmG2iib5tpWx2rEsg',
    appId: '1:568507595325:ios:c426bc44572311b7850854',
    messagingSenderId: '568507595325',
    projectId: 'starthack-delta',
    storageBucket: 'starthack-delta.appspot.com',
    iosClientId: '568507595325-sdlc5b0cp4a3kqrac820kb0qlh0p9e72.apps.googleusercontent.com',
    iosBundleId: 'com.example.starthackDeltaBellfood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARiBBQZ8m4VXLrTegmG2iib5tpWx2rEsg',
    appId: '1:568507595325:ios:c426bc44572311b7850854',
    messagingSenderId: '568507595325',
    projectId: 'starthack-delta',
    storageBucket: 'starthack-delta.appspot.com',
    iosClientId: '568507595325-sdlc5b0cp4a3kqrac820kb0qlh0p9e72.apps.googleusercontent.com',
    iosBundleId: 'com.example.starthackDeltaBellfood',
  );
}
